name: "module-one"

on:
  push:
    paths:
      - "module-one/**"
      - ".github/workflows/module-one.yml"

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./module-one
    steps:
      - uses: actions/checkout@v1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-  
      
      - name: Install NPM dependencies
        working-directory: ${{env.working-directory}}
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |-
          yarn install            
      
      - name: Build
        working-directory: ${{env.working-directory}}
        run: |-
          yarn build
          yarn cdk synth
      
      - name: Run tests
        working-directory: ${{env.working-directory}}
        run: |-
          echo "Running unit tests"
          yarn test


  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./module-one
    needs: build
    steps:
      - uses: actions/checkout@v1
  
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-  
      
      - name: Install NPM dependencies
        working-directory: ${{env.working-directory}}
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |-
          yarn install            
      
      - name: Integration tests
        working-directory: ${{env.working-directory}}
        run: |-
          ls -la
          echo "Running integration tests"
          yarn test
