name: "module-two"

on:
  push:
    paths:
      - "module-two/**"
      - ".github/workflows/module-two.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd module-two
          echo "Building module-two"