name: "module-one"

on:
  push:
    paths:
      - "module-one/**"
      - ".github/workflows/module-one.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd module-one
          echo "Building module-one"