name: "module-one"

on:
  push:
    paths:
      - "module-one/**"
      - ".github/workflows/module-one.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |-
          cd module-one
          yarn install
          yarn build
          yarn cdk synth
      - name: Run tests
        run: |-
          cd module-one
          echo "Running unit tests"
          yarn test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Integration tests
        run: |-
          pwd
          cd module-one
          echo "Running integration tests"
          yarn test
